"""Compatibility layer exposing the historical pyIECWind API from modular internals."""

from __future__ import annotations

from .generation import EWM_ALPHA, gen_ecd, gen_edc, gen_eog, gen_ewm, gen_ews, gen_nwp, generate_all, generate_from_input_file
from .models import (
    BETA,
    CASE_PREFIXES,
    CASE_ROW_COMMENTS,
    CASE_TYPE_ORDER,
    DEFAULT_INPUT_FILENAME,
    DEFAULT_TEMPLATE_FILENAME,
    DT,
    IECParameters,
    NONE_TOKENS,
    PI,
    TRUE_TOKENS,
    FALSE_TOKENS,
    VCG,
    VERSION,
)
from .parsing import (
    FIELD_ALIASES,
    _append_condition_value,
    _build_parameters,
    _expand_case_row,
    _group_conditions_by_type,
    _normalize_case_options_text,
    _normalize_key,
    _parse_case_row,
    _parse_condition_value,
    parse_input_file,
)
from .template import format_openfast_input, write_template

__all__ = [
    "BETA",
    "CASE_PREFIXES",
    "CASE_ROW_COMMENTS",
    "CASE_TYPE_ORDER",
    "DEFAULT_INPUT_FILENAME",
    "DEFAULT_TEMPLATE_FILENAME",
    "DT",
    "EWM_ALPHA",
    "FALSE_TOKENS",
    "FIELD_ALIASES",
    "IECParameters",
    "NONE_TOKENS",
    "PI",
    "TRUE_TOKENS",
    "VCG",
    "VERSION",
    "_append_condition_value",
    "_build_parameters",
    "_expand_case_row",
    "_group_conditions_by_type",
    "_normalize_case_options_text",
    "_normalize_key",
    "_parse_case_row",
    "_parse_condition_value",
    "format_openfast_input",
    "gen_ecd",
    "gen_edc",
    "gen_eog",
    "gen_ewm",
    "gen_ews",
    "gen_nwp",
    "generate_all",
    "generate_from_input_file",
    "parse_input_file",
    "write_template",
]
