"""Wind condition generators and .wnd writing."""

from __future__ import annotations

import math
import re
from pathlib import Path

import numpy as np

from .models import BETA, DT, EWM_ALPHA, IECParameters, PI, VCG, VERSION
from .parsing import parse_input_file


class WindFileWriter:
    """Build and save an InflowWind-compatible .wnd file."""

    TAB = "\t"

    def __init__(self, filepath: Path, params: IECParameters) -> None:
        self.filepath = filepath
        self.params = params
        self._lines: list[str] = []

    def _write(self, text: str = "") -> None:
        self._lines.append(text)

    def file_header(self) -> None:
        self._write(f"! This file was generated by pyIECWind v{VERSION}.")
        self._write("! Wind condition defined by IEC 61400-1.")

    def wind_header(self, condition_name: str) -> None:
        p = self.params
        lc = p.len_convert
        lu = p.len_unit
        self._write(f"! IEC Turbine Class {p.wtc}, Turbulence Category {p.catg.upper()}")
        self._write("! ----------------------------------------------------------")
        self._write(f"! Rotor diameter = {p.dia * lc:.1f} {lu}.")
        self._write(f"! {p.hh * lc:.1f} {lu} hub height yields {p.turb_scale:.1f} {lu} turbulence scale.")
        self._write("! ----------------------------------------------------------")
        self._write(f"! IEC Condition: {condition_name}.")
        self._write("! Stats for this wind file:")

    def time_header(self, duration: float) -> None:
        self._write(f"!     The transient occurs over {duration:.1f} seconds.")

    def gust_header(self, v_gust_max: float, vhub: float, t_max: float) -> None:
        p = self.params
        lc = p.len_convert
        su = p.spd_unit
        self._write("!")
        self._write(f"!     The maximum gust speed is {v_gust_max * lc:.3f} {su}.")
        self._write(f"!     The maximum total wind speed is {(v_gust_max + vhub) * lc:.3f} {su}.")
        self._write(f"!     This maximum occurs at {t_max:.3f} seconds.")

    def direction_header(self, max_dir_deg: float, t_max: float) -> None:
        self._write("!")
        self._write(f"!     The extreme direction change is {max_dir_deg:.2f} degrees.")
        self._write(f"!     This extreme occurs at {t_max:.2f} seconds.")

    def shear_header(self, dir_sign: float, is_horizontal: bool, shr_max: float, t_max: float) -> None:
        orient = "horizontal" if is_horizontal else "vertical"
        sign_word = "positive" if dir_sign > 0.0 else "negative"
        self._write("!")
        self._write(f"!     The extreme linear {orient} wind shear is {dir_sign * shr_max:.3f}.")
        self._write(f"!     This extreme occurs at {t_max:.2f} seconds.")
        self._write(f"!     This sign of the shear is {sign_word}.")

    def slope_header(self) -> None:
        self._write("!")
        self._write(f"!     The wind inflow inclination angle is {self.params.slope_deg:.1f} degrees to the horizontal.")

    def nwp_header(self, vhub: float) -> None:
        p = self.params
        self._write(f"!     The steady wind speed is {vhub * p.len_convert:.2f} {p.spd_unit}.")

    def ewm_header(self, vhub: float) -> None:
        p = self.params
        self._write(f"!     The steady extreme wind speed is {vhub * p.len_convert:.2f} {p.spd_unit}.")

    def col_headers(self) -> None:
        t = self.TAB
        su = f"({self.params.spd_unit})"
        self._write("! ----------------------------------------------------------")
        self._write(f"! Time{t}Wind{t}Wind{t}Vertical{t}Horiz.{t}Pwr.Law{t}Lin.Vert.{t}Gust")
        self._write(f"!{t}Speed{t}Dir{t}Speed{t}Shear{t}Vert.Shr{t}Shear{t}Speed")
        self._write(f"!(sec){t}{su}{t}(deg){t}{su}{t}{t}{t}{t}{su}")

    def data_row(
        self,
        time: float,
        wind_spd: float,
        wind_dir: float,
        vert_spd: float,
        horiz_shear: float,
        alpha: float,
        lin_vert_shear: float,
        gust_spd: float,
    ) -> None:
        lc = self.params.len_convert
        values = [
            time,
            wind_spd * lc,
            wind_dir,
            vert_spd * lc,
            horiz_shear,
            alpha,
            lin_vert_shear,
            gust_spd * lc,
        ]
        self._lines.append(self.TAB.join(f"{value:9.3f}" for value in values))

    def save(self) -> None:
        self.filepath.write_text("\n".join(self._lines) + "\n", encoding="utf-8")
        print(f"  Generated: {self.filepath.name}")


def _transient_times(t1: float, duration: float) -> np.ndarray:
    step_count = round(duration / DT) + 1
    return t1 + np.arange(step_count) * DT


def _hub_components(vhub: float, slope_rad: float) -> tuple[float, float]:
    return vhub * math.cos(slope_rad), vhub * math.sin(slope_rad)


def _sigma1(turb_i: float, vhub: float) -> float:
    return turb_i * (0.75 * vhub + 5.6)


def _resolve_output_path(code: str, output_dir: str | Path | None = None) -> Path:
    if output_dir is None:
        return Path(f"{code}.wnd")
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    return output_path / f"{code}.wnd"


def gen_ecd(code: str, params: IECParameters, output_dir: str | Path | None = None) -> None:
    match = re.match(r"^ECD([+-])R([+-]?\d*\.?\d*)$", code)
    if not match:
        raise ValueError(f"Cannot parse ECD condition '{code}'. Expected format: ECD[+/-]R[+/-speed_modifier]")

    dir_sign = 1.0 if match.group(1) == "+" else -1.0
    speed_modifier = (float(match.group(2)) / params.len_convert) if match.group(2) else 0.0
    if abs(speed_modifier) > 2.0:
        raise ValueError(f"ECD speed modifier must not exceed +/-2.0 m/s. Got: {speed_modifier * params.len_convert:.2f} {params.spd_unit} [{code}]")

    vhub = params.vrated + speed_modifier
    if vhub > params.vref:
        raise ValueError(f"ECD: Vhub ({vhub:.2f} m/s) exceeds Vref ({params.vref:.2f} m/s). [{code}]")

    vhub_h, vhub_v0 = _hub_components(vhub, params.slope_rad)
    theta = (180.0 if vhub <= 4.0 else 720.0 / vhub) * dir_sign
    duration = 10.0
    times = _transient_times(params.t1, duration)
    tau = times - params.t1

    gust = 0.5 * VCG * (1.0 - np.cos(PI * tau / duration))
    gust_h = gust * math.cos(params.slope_rad)
    vertical = (vhub + gust) * math.sin(params.slope_rad)
    theta_t = 0.5 * theta * (1.0 - np.cos(PI * tau / duration))

    writer = WindFileWriter(_resolve_output_path(code, output_dir), params)
    writer.file_header()
    writer.wind_header("Extreme Coherent Gust with Direction Change")
    writer.time_header(duration)
    writer.gust_header(VCG, vhub, params.t1 + duration)
    writer.direction_header(theta, params.t1 + duration)
    writer.slope_header()
    writer.col_headers()
    writer.data_row(0.0, vhub_h, 0.0, vhub_v0, 0.0, params.alpha, 0.0, 0.0)
    for index, time in enumerate(times):
        writer.data_row(time, vhub_h, float(theta_t[index]), float(vertical[index]), 0.0, params.alpha, 0.0, float(gust_h[index]))
    writer.save()


def gen_ews(code: str, params: IECParameters, output_dir: str | Path | None = None) -> None:
    match = re.match(r"^EWS([VH])([+-])(\d+\.?\d*)$", code)
    if not match:
        raise ValueError(f"Cannot parse EWS condition '{code}'. Expected format: EWS[V/H][+/-][wind_speed]")

    is_horizontal = match.group(1) == "H"
    dir_sign = 1.0 if match.group(2) == "+" else -1.0
    vhub = float(match.group(3)) / params.len_convert
    if vhub < params.vin or vhub > params.vout:
        raise ValueError(
            f"EWS wind speed ({vhub * params.len_convert:.1f} {params.spd_unit}) must be between Vin ({params.vin * params.len_convert:.1f}) and Vout ({params.vout * params.len_convert:.1f}). [{code}]"
        )

    vhub_h, vhub_v = _hub_components(vhub, params.slope_rad)
    sigma1 = _sigma1(params.turb_intensity, vhub)
    vg50 = BETA * sigma1
    shr_max = 2.0 * (2.5 + 0.2 * vg50 * params.turb_rat ** 0.25) / vhub
    duration = 12.0
    times = _transient_times(params.t1, duration)
    tau = times - params.t1
    shear = dir_sign * 0.5 * shr_max * (1.0 - np.cos(2.0 * PI * tau / duration))
    h_shr = shear if is_horizontal else np.zeros_like(shear)
    v_shr = shear if not is_horizontal else np.zeros_like(shear)

    writer = WindFileWriter(_resolve_output_path(code, output_dir), params)
    writer.file_header()
    writer.wind_header(f"Extreme {'Horizontal' if is_horizontal else 'Vertical'} Wind Shear")
    writer.time_header(duration)
    writer.shear_header(dir_sign, is_horizontal, shr_max, params.t1 + duration)
    writer.slope_header()
    writer.col_headers()
    writer.data_row(0.0, vhub_h, 0.0, vhub_v, 0.0, params.alpha, 0.0, 0.0)
    for index, time in enumerate(times):
        writer.data_row(time, vhub_h, 0.0, vhub_v, float(h_shr[index]), params.alpha, float(v_shr[index]), 0.0)
    writer.save()


def gen_eog(code: str, params: IECParameters, output_dir: str | Path | None = None) -> None:
    match = re.match(r"^EOG([IOR])([+-]?\d*\.?\d*)$", code)
    if not match:
        raise ValueError(f"Cannot parse EOG condition '{code}'. Expected format: EOG[I/O/R][+/-speed_modifier]")

    speed_key = match.group(1)
    modifier_text = match.group(2)
    if speed_key == "I":
        vhub = params.vin
    elif speed_key == "O":
        vhub = params.vout
    else:
        speed_modifier = (float(modifier_text) / params.len_convert) if modifier_text else 0.0
        if abs(speed_modifier) > 2.0:
            raise ValueError(f"EOG speed modifier must not exceed +/-2.0 m/s. Got: {speed_modifier * params.len_convert:.2f} {params.spd_unit} [{code}]")
        vhub = params.vrated + speed_modifier

    vhub_h, vhub_v0 = _hub_components(vhub, params.slope_rad)
    sigma1 = _sigma1(params.turb_intensity, vhub)
    gust_max = min(1.35 * (params.ve1 - vhub), 3.3 * sigma1 / (1.0 + 0.1 * params.turb_rat))
    duration = 10.5
    times = _transient_times(params.t1, duration)
    tau = times - params.t1

    gust_factor = -0.37 * gust_max * np.sin(3.0 * PI * tau / duration) * (1.0 - np.cos(2.0 * PI * tau / duration))
    gust_h = gust_factor * math.cos(params.slope_rad)
    vertical = (vhub + gust_factor) * math.sin(params.slope_rad)

    writer = WindFileWriter(_resolve_output_path(code, output_dir), params)
    writer.file_header()
    writer.wind_header("Extreme Operating Gust")
    writer.time_header(duration)
    writer.gust_header(2 * 0.37 * gust_max, vhub, params.t1 + 0.5 * duration)
    writer.slope_header()
    writer.col_headers()
    writer.data_row(0.0, vhub_h, 0.0, vhub_v0, 0.0, params.alpha, 0.0, 0.0)
    for index, time in enumerate(times):
        writer.data_row(time, vhub_h, 0.0, float(vertical[index]), 0.0, params.alpha, 0.0, float(gust_h[index]))
    writer.save()


def gen_edc(code: str, params: IECParameters, output_dir: str | Path | None = None) -> None:
    match = re.match(r"^EDC([+-])([IOR])([+-]?\d*\.?\d*)$", code)
    if not match:
        raise ValueError(f"Cannot parse EDC condition '{code}'. Expected format: EDC[+/-][I/O/R][+/-speed_modifier]")

    dir_sign = 1.0 if match.group(1) == "+" else -1.0
    speed_key = match.group(2)
    modifier_text = match.group(3)
    if speed_key == "I":
        vhub = params.vin
    elif speed_key == "O":
        vhub = params.vout
    else:
        speed_modifier = (float(modifier_text) / params.len_convert) if modifier_text else 0.0
        if abs(speed_modifier) > 2.0:
            raise ValueError(f"EDC speed modifier must not exceed +/-2.0 m/s. Got: {speed_modifier * params.len_convert:.2f} {params.spd_unit} [{code}]")
        vhub = params.vrated + speed_modifier

    vhub_h, vhub_v = _hub_components(vhub, params.slope_rad)
    sigma1 = _sigma1(params.turb_intensity, vhub)
    theta = math.degrees(4.0 * math.atan(sigma1 / (vhub * (1.0 + 0.1 * params.turb_rat)))) * dir_sign
    duration = 6.0
    times = _transient_times(params.t1, duration)
    tau = times - params.t1
    theta_t = 0.5 * theta * (1.0 - np.cos(PI * tau / duration))

    writer = WindFileWriter(_resolve_output_path(code, output_dir), params)
    writer.file_header()
    writer.wind_header("Extreme Direction Change")
    writer.time_header(duration)
    writer.direction_header(theta, params.t1 + duration)
    writer.slope_header()
    writer.col_headers()
    writer.data_row(0.0, vhub_h, 0.0, vhub_v, 0.0, params.alpha, 0.0, 0.0)
    for index, time in enumerate(times):
        writer.data_row(time, vhub_h, float(theta_t[index]), vhub_v, 0.0, params.alpha, 0.0, 0.0)
    writer.save()


def gen_nwp(code: str, params: IECParameters, output_dir: str | Path | None = None) -> None:
    match = re.match(r"^NWP(\d+\.?\d*)$", code)
    if not match:
        raise ValueError(f"Cannot parse NWP condition '{code}'. Expected format: NWP[wind_speed_in_m/s]")

    vhub = float(match.group(1))
    vhub_h, vhub_v = _hub_components(vhub, params.slope_rad)

    writer = WindFileWriter(_resolve_output_path(code, output_dir), params)
    writer.file_header()
    writer.wind_header("Normal Wind Profile")
    writer.nwp_header(vhub)
    writer.slope_header()
    writer.col_headers()
    writer.data_row(0.0, vhub_h, 0.0, vhub_v, 0.0, params.alpha, 0.0, 0.0)
    writer.save()


def gen_ewm(code: str, params: IECParameters, output_dir: str | Path | None = None) -> None:
    match = re.match(r"^EWM(50|01)$", code)
    if not match:
        raise ValueError(f"Cannot parse EWM condition '{code}'. Expected format: EWM50 or EWM01")

    if match.group(1) == "50":
        vhub = params.ve50
        recurrence = "50-year"
    else:
        vhub = params.ve1
        recurrence = "1-year"

    vhub_h, vhub_v = _hub_components(vhub, params.slope_rad)
    writer = WindFileWriter(_resolve_output_path(code, output_dir), params)
    writer.file_header()
    writer.wind_header(f"{recurrence} Extreme Wind Model")
    writer.ewm_header(vhub)
    writer.slope_header()
    writer.col_headers()
    writer.data_row(0.0, vhub_h, 0.0, vhub_v, 0.0, EWM_ALPHA, 0.0, 0.0)
    writer.save()


_GENERATORS = {
    "ECD": gen_ecd,
    "EWS": gen_ews,
    "EOG": gen_eog,
    "EDC": gen_edc,
    "NWP": gen_nwp,
    "EWM": gen_ewm,
}


def generate_all(params: IECParameters, output_dir: str | Path | None = None) -> int:
    count = 0
    for code in params.conditions:
        generator = _GENERATORS.get(code[:3])
        if generator is None:
            print(f"ERROR: Unknown condition type '{code[:3]}' in code '{code}'. Skipping.")
            continue
        try:
            generator(code, params, output_dir=output_dir)
            count += 1
        except ValueError as exc:
            print(f"ERROR generating '{code}': {exc}")
    return count


def generate_from_input_file(
    input_file: str | Path,
    *,
    output_dir: str | Path | None = None,
) -> tuple[IECParameters, int]:
    params = parse_input_file(input_file)
    return params, generate_all(params, output_dir=output_dir)
