from __future__ import annotations

import uuid
from pathlib import Path

from pyiecwind.core import IECParameters


class WorkspaceTestCaseMixin:
    def workspace_tempdir(self) -> Path:
        tests_dir = Path(__file__).resolve().parent
        scratch_root = tests_dir / ".tmp"
        scratch_root.mkdir(exist_ok=True)
        workdir = scratch_root / f"case_{uuid.uuid4().hex}"
        workdir.mkdir()
        return workdir


def default_parameters(*, conditions: list[str] | None = None, si_unit: bool = True) -> IECParameters:
    return IECParameters(
        si_unit=si_unit,
        t1=40.0,
        wtc=2,
        catg="B",
        slope_deg=0.0,
        iec_edition=3,
        hh=80.0,
        dia=80.0,
        vin=4.0,
        vrated=10.0,
        vout=24.0,
        conditions=conditions or ["EWM50"],
    )


def openfast_case_table_text(
    *,
    si_unit: str = "True",
    t1: str = "40.000",
    wtc: str = "2",
    catg: str = "B",
    slope_deg: str = "0.000",
    iec_edition: str = "3",
    hh: str = "80.000",
    dia: str = "80.000",
    vin: str = "4.000",
    vrated: str = "10.000",
    vout: str = "24.000",
    case_rows: list[str] | None = None,
) -> str:
    rows = case_rows or [
        "ECD             True   [+R]                     - ECD row",
        "EWS             True   [V+12.0]                - EWS row",
        "EOG             True   [R+2.0]                 - EOG row",
        "EDC             True   [+R]                    - EDC row",
        "NWP             True   [23.7]                  - NWP row",
        "EWM             True   [50]                    - EWM row",
    ]
    return "\n".join(
        [
            "! ------- pyIECWind Input File -----------------------------------------------",
            "! Generated by pyIECWind in an OpenFAST-style table layout.",
            "! Each active data row follows: value  key  - comment",
            "",
            "! General",
            "! -------",
            "",
            f"{si_unit:<15} si_unit      - unit system",
            f"{t1:<15} t1           - transient start time [s]",
            f"{wtc:<15} wtc          - wind turbine class",
            f"{catg:<15} catg         - turbulence category",
            f"{slope_deg:<15} slope_deg    - inflow angle [deg]",
            f"{iec_edition:<15} iec_edition  - IEC edition",
            "",
            "! Turbine",
            "! -------",
            "",
            f"{hh:<15} hh           - hub height [m]",
            f"{dia:<15} dia          - rotor diameter [m]",
            "",
            "! Operating Speeds",
            "! ----------------",
            "",
            f"{vin:<15} vin          - cut-in wind speed",
            f"{vrated:<15} vrated       - rated wind speed",
            f"{vout:<15} vout         - cut-out wind speed",
            "",
            "! Cases",
            "! -----",
            "",
            "! Format: case_type  use_case  options_array  - allowed options and notes",
            "",
            *rows,
            "",
        ]
    )
