from __future__ import annotations

import unittest
from pathlib import Path

from pyiecwind.core import format_openfast_input, generate_from_input_file, parse_input_file, write_template

from helpers import WorkspaceTestCaseMixin


class PackageSmokeTests(WorkspaceTestCaseMixin, unittest.TestCase):

    def test_template_writer_creates_file(self) -> None:
        tmp = self.workspace_tempdir()
        dest = tmp / "template.ipt"
        write_template(dest)
        self.assertTrue(dest.exists())
        contents = dest.read_text(encoding="utf-8")
        self.assertIn("! Cases", contents)
        self.assertIn("ECD", contents)
        self.assertIn("use_case", contents)
        self.assertIn("! Operating Speeds", contents)
        self.assertIn("options_array", contents)

    def test_generate_from_input_file_writes_outputs(self) -> None:
        tmp_path = self.workspace_tempdir()
        input_file = tmp_path / "case.ipt"
        output_dir = tmp_path / "out"
        input_file.write_text(
            "\n".join(
                [
                    "! ------- pyIECWind Input File -----------------------------------------------",
                    "! Generated by pyIECWind in an OpenFAST-style table layout.",
                    "! Each active data row follows: value  key  - comment",
                    "",
                    "! General",
                    "! -------",
                    "",
                    "True            si_unit      - SI units",
                    "40.000          t1           - transient start time [s]",
                    "2               wtc          - wind turbine class",
                    "B               catg         - turbulence category",
                    "0.000           slope_deg    - inflow angle [deg]",
                    "3               iec_edition  - IEC edition",
                    "",
                    "! Turbine",
                    "! -------",
                    "",
                    "80.000          hh           - hub height [m]",
                    "80.000          dia          - rotor diameter [m]",
                    "",
                    "! Operating Speeds",
                    "! ----------------",
                    "",
                    "4.000           vin          - cut-in wind speed [m/s]",
                    "10.000          vrated       - rated wind speed [m/s]",
                    "24.000          vout         - cut-out wind speed [m/s]",
                    "",
                    "! Cases",
                    "! -----",
                    "",
                    "EWM             True   [50]                    - 50-year extreme wind model",
                    "NWP             True   [10.0]                  - normal wind profile",
                    "ECD             False  [+R, -R]                - disabled row",
                ]
            ),
            encoding="utf-8",
        )

        params, count = generate_from_input_file(input_file, output_dir=output_dir)

        self.assertEqual(count, 2)
        self.assertEqual(params.wtc, 2)
        self.assertTrue((output_dir / "EWM50.wnd").exists())
        self.assertTrue((output_dir / "NWP10.0.wnd").exists())
        self.assertFalse((output_dir / "EWM01.wnd").exists())

    def test_openfast_formatter_round_trip(self) -> None:
        tmp_path = self.workspace_tempdir()
        input_file = tmp_path / "roundtrip.ipt"
        input_file.write_text(
            format_openfast_input(
                parse_input_file(Path("examples") / "sample_case.ipt")
            ),
            encoding="utf-8",
        )

        params = parse_input_file(input_file)
        self.assertEqual(params.conditions[0], "ECD+R")
        self.assertEqual(params.catg, "B")


if __name__ == "__main__":
    unittest.main()
