"""Independent reference (oracle) checks.

The golden corpus protects against accidental regressions, but it is generated by
the same code under test. These tests add a second, independent calculation
layer: each case family's headline physical quantity is recomputed here directly
from the IEC 61400-1 equations -- with the standard's reference values
transcribed independently below -- and compared against the generated output.

A coding bug in a generator (wrong coefficient, sign, or unit) would make these
disagree even though the golden files still matched themselves.
"""

from __future__ import annotations

import math
import re
import unittest

from helpers import WorkspaceTestCaseMixin, default_parameters
from pyiecwind.generation import gen_ecd, gen_edc, gen_eog, gen_ewm, gen_ews, gen_nwp

# --- IEC 61400-1 reference values, transcribed independently of the package ---
IEC_VREF = {1: 50.0, 2: 42.5, 3: 37.5}  # reference wind speed by turbine class [m/s]
IEC_IREF = {"A": 0.16, "B": 0.14, "C": 0.12}  # reference turbulence intensity
IEC_VCG = 15.0  # coherent gust magnitude [m/s]
IEC_BETA = 6.4  # EWS parameter


def _lambda(hub_height: float) -> float:
    return 0.7 * hub_height if hub_height < 60.0 else 42.0


def _sigma1(iref: float, vhub: float) -> float:
    return iref * (0.75 * vhub + 5.6)


class OracleTests(WorkspaceTestCaseMixin, unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = self.workspace_tempdir()
        # Class 2, category B, edition 3, hub height 80 m, rotor 80 m.
        self.params = default_parameters()
        self.vref = IEC_VREF[self.params.wtc]
        self.iref = IEC_IREF[self.params.catg]
        self.lam = _lambda(self.params.hh)
        self.turb_rat = self.params.dia / self.lam

    def _text(self, generator, code: str) -> str:
        return generator(code, self.params, output_dir=self.tmp).read_text(encoding="utf-8")

    def _header_value(self, text: str, pattern: str) -> float:
        match = re.search(pattern, text)
        assert match is not None, f"pattern {pattern!r} not found"
        return float(match.group(1))

    def _last_row(self, text: str) -> list[float]:
        rows = [ln for ln in text.splitlines() if ln and not ln.startswith("!")]
        return [float(token) for token in rows[-1].split()]

    def test_ewm_extreme_wind_speeds(self) -> None:
        ve50 = 1.4 * self.vref
        ve1 = 0.8 * ve50
        self.assertAlmostEqual(self._last_row(self._text(gen_ewm, "EWM50"))[1], ve50, places=3)
        self.assertAlmostEqual(self._last_row(self._text(gen_ewm, "EWM01"))[1], ve1, places=3)

    def test_nwp_steady_speed(self) -> None:
        self.assertAlmostEqual(self._last_row(self._text(gen_nwp, "NWP10.0"))[1], 10.0, places=3)

    def test_ecd_direction_and_gust(self) -> None:
        text = self._text(gen_ecd, "ECD+R")  # vhub = vrated = 10 m/s > 4
        expected_theta = 720.0 / self.params.vrated
        self.assertAlmostEqual(
            self._header_value(text, r"extreme direction change is (-?\d+\.\d+) degrees"),
            expected_theta,
            places=2,
        )
        self.assertAlmostEqual(self._header_value(text, r"maximum gust speed is (-?\d+\.\d+)"), IEC_VCG, places=3)
        self.assertAlmostEqual(self._last_row(text)[2], expected_theta, places=2)

    def test_edc_direction(self) -> None:
        vhub = self.params.vrated
        sigma1 = _sigma1(self.iref, vhub)
        theta = math.degrees(4.0 * math.atan(sigma1 / (vhub * (1.0 + 0.1 * self.turb_rat))))
        text = self._text(gen_edc, "EDC+R")
        self.assertAlmostEqual(
            self._header_value(text, r"extreme direction change is (-?\d+\.\d+) degrees"),
            theta,
            places=2,
        )
        self.assertAlmostEqual(self._last_row(text)[2], theta, places=2)

    def test_eog_gust_amplitude(self) -> None:
        vhub = self.params.vrated
        sigma1 = _sigma1(self.iref, vhub)
        ve1 = 0.8 * 1.4 * self.vref
        gust_max = min(1.35 * (ve1 - vhub), 3.3 * sigma1 / (1.0 + 0.1 * self.turb_rat))
        text = self._text(gen_eog, "EOGR")
        self.assertAlmostEqual(
            self._header_value(text, r"maximum gust speed is (-?\d+\.\d+)"),
            2.0 * 0.37 * gust_max,
            places=3,
        )

    def test_ews_shear(self) -> None:
        vhub = 12.0  # EWSV+12.0
        sigma1 = _sigma1(self.iref, vhub)
        vg50 = IEC_BETA * sigma1
        shr_max = 2.0 * (2.5 + 0.2 * vg50 * self.turb_rat**0.25) / vhub
        text = self._text(gen_ews, "EWSV+12.0")
        self.assertAlmostEqual(
            self._header_value(text, r"extreme linear \w+ wind shear is (-?\d+\.\d+)"),
            shr_max,
            places=3,
        )


if __name__ == "__main__":
    unittest.main()
